### ISSUE TITLE
0014-Cross-build-with-mingw32.patch sets distrib-specific compiler prefix

### ISSUE THREAD

**Issue by aderbenev** [epicsdeb/epics-base#12] opened 2017-08-31 22:50 UTC
When building the package on Debian 7 i686 image,

```
make[5]: /usr/bin/i686-w64-mingw32-gcc: Command not found
```

Appears to be a consequence of CMPLR_PREFIX being set in patch 0014. While I assume that commenting line for Ubuntu and uncommenting line for Debian should fix the issue, I'd expect debianized source to build on Debian without modifications of this sort. What is the proper way to address this?

**Comment by mdavidsaver** [comment] 2017-08-31 22:55
yup, this is caused by 68ca398403e38793491a96257bbbc0ad698c170a.  We can either start another branch 'master-deb7' like the existing 'master-deb6', or try to figure out some makefile magic to detect which prefix to use.

**Comment by mdavidsaver** [comment] 2017-08-31 22:56
If you can build aada8e8fd43ae850749f14202f3b820c71c22e1a (3.15.3-12) the perhaps it is simplest to branch off 'master-deb7' from there.

**Comment by aderbenev** [comment] 2017-08-31 23:04
This complication aside (which I think can be handled with $(OS) and uname), are there other reasons to create a separate branch? As I see it, whatever upstream imports or packaging modifications will come to master branch later, it will be additional effort to also put them in that 'master-deb7'.

**Comment by mdavidsaver** [comment] 2017-08-31 23:06
A branch would remove the possibility of accidental breakage from subsequent changes.  Of course it also adds a step for fixes and updated patches.

**Comment by aderbenev** [comment] 2017-08-31 23:39
Doesn't that awfully sound like extra work... just how nice it is to have one branch which magically builds everywhere. Yet the build succeeds with aada8e8fd43ae850749f14202f3b820c71c22e1a.

**Comment by mark0n** [comment] 2017-09-26 02:43
Debian 7's support ends in May 2018. Until then we probably want to support it. But after that date we want to move on without too much hassle. How about a patch on top of what we have so far that adds the necessary magic? It could easily be dropped in May.

Theoretically branching works as well but then we are stuck with all these branches. What do we do with this new branch after May 2018? Delete it? Then we would lose history. Keep it forever? That would clutter things. The best solution might be to create a tag instead.

**Comment by mark0n** [comment] 2018-09-18 22:09
LTS for Debian 7 has ceased on May 31st. I'm thus closing this ticket. @aderbenev, if you still need this I would recommend to apply a patch/create a branch in your internal repo.

**Closed by mark0n** 2018-09-18 22:09 UTC
Labels: bug
